# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: bizzy-front

plugins:
  - serverless-s3-remover
  - serverless-s3-sync
  - serverless-certificate-creator

custom:
  defaultRegion: us-east-1
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  objectPrefix: '${self:service}-${self:custom.currentStage}'
  bucketName: dev-bizzy.com
  # Normally use this value, we volontary custom bucketName for the first branch/architecture
  # bucketName: ${self:custom.domainName}
  remover:
     buckets:
       - ${self:custom.bucketName}
       - ${self:custom.bucketName}-accesslogs
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: build

  domainName:
    staging: 'staging-front.bizzy.studio'
    dev: 'dev-front.bizzy.studio'
    prod: 'bizzy.studio'
  hostZoneId: Z031944535CSP0ARG1684
  # certInfoFileName: cert-info.yml


  customCertificate:
    certificateName: ${self:custom.domainName.${self:custom.currentStage}}
    hostedZoneId: ${self:custom.hostZoneId}
    region: 'us-east-1' # required for using CloudFront with AWS Certificate Manager
    # writeCertInfoToFile: true
    # certInfoFileName: ${self:custom.certInfoFileName}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.currentStage}
  region: ${self:custom.region}

package:
   exclude:
      - 'node_modules/**'
      - 'build/**'
      - 'public/**'

resources:
  Resources:
        BucketAccessLogs:
          Type: 'AWS::S3::Bucket'
          Properties:
            BucketName: ${self:custom.bucketName}-accesslogs
            AccessControl: LogDeliveryWrite
        BizzyApp:
          Type: 'AWS::S3::Bucket'
          Properties:
            BucketName: ${self:custom.bucketName}
            WebsiteConfiguration:
              ErrorDocument: "error.html"
              IndexDocument: "index.html"
            LoggingConfiguration:
              DestinationBucketName:
                Ref: BucketAccessLogs
        S3AccessPolicy:
            Type: AWS::S3::BucketPolicy
            DependsOn:
              - BizzyApp
              - CloudFrontOriginAccessIdentity
            Properties:
              Bucket:
                Ref: BizzyApp
              PolicyDocument:
                Statement:
                  - Sid: PublicReadGetObject
                    Effect: Allow
                    Principal: '*'
                    Action:
                      - s3:GetObject
                    Resource:
                      - Fn::Join: [
                          '', [
                            'arn:aws:s3:::',
                            {
                              'Ref': 'BizzyApp'
                            },
                            '/*'
                          ]
                        ]
        CloudFrontOriginAccessIdentity:
              Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
              Properties:
                CloudFrontOriginAccessIdentityConfig:
                  Comment: "BizzyApp CloudFrontOrigin"
        CloudFrontDistribution:
              Type: 'AWS::CloudFront::Distribution'
              DependsOn:
                - BizzyApp
                - CloudFrontOriginAccessIdentity
              Properties:
                DistributionConfig:
                  Origins:
                    - DomainName: ${self:custom.bucketName}.s3.amazonaws.com
                      OriginPath: ''
                      Id: S3BucketOrigin
                      S3OriginConfig:
                        OriginAccessIdentity:
                          Fn::Join:
                            - ''
                            - 
                              - 'origin-access-identity/cloudfront/'
                              - Ref: CloudFrontOriginAccessIdentity
                  Comment: 'CloudFront origin for ${self:custom.bucketName}'
                  Aliases:
                      - ${self:custom.domainName.${self:custom.currentStage}}
                  CustomErrorResponses:
                    - ErrorCode: 404
                      ResponseCode: 200
                      ErrorCachingMinTTL: 0
                      ResponsePagePath: /index.html
                    - ErrorCode: 403
                      ResponseCode: 200
                      ErrorCachingMinTTL: 0
                      ResponsePagePath: /index.html
                  DefaultCacheBehavior:
                    AllowedMethods:
                      - GET
                      - HEAD
                      - OPTIONS
                    TargetOriginId: S3BucketOrigin
                    Compress: true
                    ForwardedValues:
                      QueryString: 'false'
                      Cookies:
                        Forward: none
                    ViewerProtocolPolicy: redirect-to-https
                  DefaultRootObject: index.html
                  Enabled: 'true'
                  HttpVersion: 'http2'
                  PriceClass: 'PriceClass_100'
                  ViewerCertificate:
                      # CloudFrontDefaultCertificate: true
                      AcmCertificateArn: ${certificate:${self:custom.customCertificate.certificateName}:CertificateArn}
                      SslSupportMethod: sni-only
        WebsiteDNSName:
          Type: 'AWS::Route53::RecordSetGroup'
          Properties:
            HostedZoneId: ${self:custom.hostZoneId}
            RecordSets:
              - Name: ${self:custom.domainName.${self:custom.currentStage}}
                Type: A
                AliasTarget:
                  # HostedZoneId
                  # Z2FDTNDATAQYW2 is a special value for Cloudfront cloudfront distribution, see documentation block Distribution CloudFront
                  # doc: https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
                  HostedZoneId: Z2FDTNDATAQYW2
                  DNSName:
                    Fn::GetAtt:
                      - CloudFrontDistribution
                      - DomainName
                  EvaluateTargetHealth: false
