# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: bizzy

frameworkVersion: '1'

plugins:
  - '@silvermine/serverless-plugin-cloudfront-lambda-edge'
  - serverless-s3-remover
  - serverless-s3-sync

custom:
  defaultRegion: us-east-1
  defaultStage: ${opt:stage}
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}
  objectPrefix: '${self:service}-${self:custom.stage}'
  domainName: dev-bizzy.com
  bucketName: ${self:custom.domainName}
  remover:
     buckets:
       - ${self:custom.bucketName}
       - ${self:custom.bucketName}-accesslogs
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: build

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  profile: bizzy_deploy_front_dev

package:
   exclude:
      - 'node_modules/**'
      - 'build/**'
      - 'public/**'

resources:
  Resources:
        BucketAccessLogs:
          Type: 'AWS::S3::Bucket'
          Properties:
            BucketName: ${self:custom.bucketName}-accesslogs
            AccessControl: LogDeliveryWrite
        BizzyApp:
          Type: 'AWS::S3::Bucket'
          Properties:
            BucketName: ${self:custom.bucketName}
            WebsiteConfiguration:
              ErrorDocument: "error.html"
              IndexDocument: "index.html"
            LoggingConfiguration:
              DestinationBucketName:
                Ref: BucketAccessLogs
        S3AccessPolicy:
            Type: AWS::S3::BucketPolicy
            DependsOn:
              - BizzyApp
              - CloudFrontOriginAccessIdentity
            Properties:
              Bucket:
                Ref: BizzyApp
              PolicyDocument:
                Statement:
                  - Sid: PublicReadGetObject
                    Effect: Allow
                    Principal: '*'
                    Action:
                      - s3:GetObject
                    Resource:
                      - Fn::Join: [
                          '', [
                            'arn:aws:s3:::',
                            {
                              'Ref': 'BizzyApp'
                            },
                            '/*'
                          ]
                        ]
        CloudFrontOriginAccessIdentity:
              Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
              Properties:
                CloudFrontOriginAccessIdentityConfig:
                  Comment: "BizzyApp CloudFrontOrigin"
        CloudFrontDistribution:
              Type: 'AWS::CloudFront::Distribution'
              DependsOn:
                - BizzyApp
                - CloudFrontOriginAccessIdentity
              Properties:
                DistributionConfig:
                  Origins:
                    - DomainName: ${self:custom.bucketName}.s3.amazonaws.com
                      OriginPath: ''
                      Id: S3BucketOrigin
                      S3OriginConfig:
                        OriginAccessIdentity:
                          Fn::Join:
                            - ''
                            - 
                              - 'origin-access-identity/cloudfront/'
                              - Ref: CloudFrontOriginAccessIdentity
                  Comment: 'CloudFront origin for ${self:custom.bucketName}'
                  CustomErrorResponses:
                    - ErrorCode: 404
                      ResponseCode: 200
                      ErrorCachingMinTTL: 0
                      ResponsePagePath: /index.html
                    - ErrorCode: 403
                      ResponseCode: 200
                      ErrorCachingMinTTL: 0
                      ResponsePagePath: /index.html
                  DefaultCacheBehavior:
                    AllowedMethods:
                      - GET
                      - HEAD
                      - OPTIONS
                    TargetOriginId: S3BucketOrigin
                    Compress: true
                    ForwardedValues:
                      QueryString: 'false'
                      Cookies:
                        Forward: none
                    ViewerProtocolPolicy: redirect-to-https
                  DefaultRootObject: index.html
                  Enabled: 'true'
                  HttpVersion: 'http2'
                  PriceClass: 'PriceClass_100'
                  ViewerCertificate:
                      CloudFrontDefaultCertificate: true